export const GET_USER = "GET_USER"; 
export const GET_USERS = "GET_USERS"; 
export const ADD_USER = "ADD_USER"; 
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"

export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const GET_PRODUCT_SIZE = "GET_PRODUCT_SIZE"
export const GET_PRODUCT_CATEGORY = "GET_PRODUCT_CATEGORY"
export const GET_PRODUCT_TYPE = "GET_PRODUCT_TYPE"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const ADD_CART_PRODUCT = "ADD_CART_PRODUCT"
export const CART_PRODUCT = "CART_PRODUCT"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const SET_IMAGE_URL = "SET_IMAGE_URL"
export const GET_SIMPLE_PRODUCT = "GET_SIMPLE_PRODUCT"
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"

export const TOGGLE_CART = "TOGGLE_CART"
export const RESET_PRODUCT_IMAGE = "RESET_PRODUCT_IMAGE"
export const HANDLE_PAGINATION = "HANDLE_PAGINATION"